General:
    comment: 
    seed: 2021
    fp16: True
    amp_level: O2
    precision: 16 
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 300 
    grad_acc: 2
    frozen_bn: False
    patience: 300
    server: test #train #test
    log_path: logs/

Data:
    dataset_name: camel_data
    data_shuffle: False
    data_dir: /home/omnisky/sde/NanTH/IRL_Data/all_slide/features_irl/h5_files/
    label_dir: /home/omnisky/sde/NanTH/IRL_Data/all_slide/features_irl/split_L.csv
    fold: 1
    nfold: 99

    train_dataloader:
        batch_size: 1 
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

Model:
    name: TransMIL
    n_classes: 5
    asynchronous: 0


Optimizer:
    opt: lookahead_radam
    lr: 0.0002
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

